import 'package:flutter/material.dart';

class DocumentationData {
  static final getData = [
    {
      'id': 1,
      'time': '10:20',
      'date': '20.20.20202',
      'text': 'Short Description about document.',
      'owner': 'Manuel',
      'documentation': 'Document 1',
      'icon': Icons.insert_drive_file,
      'iconColor': Color(0xfff20074),
      'changeColor': Colors.grey,
    },
    {
      'id': 2,
      'time': '10:20',
      'date': '20.20.20202',
      'text': 'Short Description about document.',
      'owner': 'Manuel',
      'documentation': 'Document 2',
      'icon': Icons.insert_drive_file,
      'iconColor': Color(0xfff20074),
      'changeColor': Colors.grey,
    },
    {
      'id': 3,
      'time': '10:20',
      'date': '20.20.20202',
      'text': 'Short Description about document.',
      'owner': 'Manuel',
      'documentation': 'Document 3',
      'icon': Icons.insert_drive_file,
      'iconColor': Color(0xfff20074),
      'changeColor': Colors.grey,
    },
    {
      'id': 4,
      'time': '10:20',
      'date': '20.20.20202',
      'text': 'Short Description about document.',
      'owner': 'Manuel',
      'documentation': 'Document 4',
      'icon': Icons.insert_drive_file,
      'iconColor': Color(0xfff20074),
      'changeColor': Colors.grey,
    },
    {
      'id': 5,
      'time': '10:20',
      'date': '20.20.20202',
      'text': 'Short Description about document.',
      'owner': 'Manuel',
      'documentation': 'Document 5',
      'icon': Icons.insert_drive_file,
      'iconColor': Color(0xfff20074),
      'changeColor': Colors.grey,
    },
  ];
}
